name: None
title: None
email: todjiang@gmail.com

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
#redcarpet
#rdiscount
rouge: true
encoding: utf-8
permalink: none
# permalink:
# none /:categories/:title.html
# date  /:categories/:year/:month/:day/:title.html
kramdown:
  input: GFM

url: "http://iamtod.com" # the base hostname & protocol for your site
