name: 01010100 01101111 01100100
markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
#redcarpet
#rdiscount
pygments: true
encoding: utf-8
permalink: none
# permalink:
# none /:categories/:title.html
# date  /:categories/:year/:month/:day/:title.html
kramdown:
  input: GFM
